/* Copyright (c) 2016, David Hauweele <david@hauweele.net>
   All rights reserved.

   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions are met:

    1. Redistributions of source code must retain the above copyright notice, this
       list of conditions and the following disclaimer.
    2. Redistributions in binary form must reproduce the above copyright notice,
       this list of conditions and the following disclaimer in the documentation
       and/or other materials provided with the distribution.

   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
   ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
   WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
   DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
   ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
   (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
   LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
   (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef MON_CT_POWERCYCLE_H_
#define MON_CT_POWERCYCLE_H_

enum {
  MON_ST_POWERCYCLE_RADIO_ON_1,
  MON_ST_POWERCYCLE_RADIO_OFF_1,
  MON_ST_POWERCYCLE_RADIO_OFF_2,
  MON_ST_POWERCYCLE_RADIO_OFF_3,
  MON_ST_POWERCYCLE_RADIO_OFF_4,
  MON_ST_POWERCYCLE_RADIO_CCA_1,
  MON_ST_POWERCYCLE_RADIO_CCA_2,
  MON_ST_POWERCYCLE_LISTEN_TIME_AFTER_PACKET_DETECTED,
  MON_ST_POWERCYCLE_MAX_SILENCE,
  MON_ST_POWERCYCLE_FASTSLEEP,
  MON_ST_POWERCYCLE_PACKET_SEEN,
  MON_ST_POWERCYCLE_SILENCE,
  MON_ST_POWERCYCLE_ACTIVITY,
  MON_ST_POWERCYCLE_RECEIVING,
  MON_ST_POWERCYCLE_PENDING,
  MON_ST_POWERCYCLE_NEXT_CCA,
  MON_ST_POWERCYCLE_NEXT_CCA_CHECK,
  MON_ST_POWERCYCLE_NEXT_POWERCYCLE,
  MON_ST_POWERCYCLE_ARCH_SLEEP,

  MON_ST_POWERCYCLE_FSM_START,
  MON_ST_POWERCYCLE_FSM_PROBES,
  MON_ST_POWERCYCLE_FSM_PROBE,
  MON_ST_POWERCYCLE_FSM_SEEN,
  MON_ST_POWERCYCLE_FSM_ACTIVITY_CHECK,
  MON_ST_POWERCYCLE_FSM_PERIODS_CHECK,
  MON_ST_POWERCYCLE_FSM_PENDING,
  MON_ST_POWERCYCLE_FSM_SLEEP_END,
  MON_ST_POWERCYCLE_FSM_END,
};

enum {
  MON_ENT_CONTIKIMAC
};

#endif /* MON_CT_POWERCYCLE_H_ */
